---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisionamento EC2

Parameters:
  TagsProject:
    Type: String
    Default: "Devops"
  TagsTeam:
    Type: String
    Default: "DO3" 
  ImageId:
    Type: String
    Default: "ami-051f8a213df8bc089"
# ami Amazon Linux 2023 AMI

Resources:
  SecurityGroupAdaHack:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Ada Hack
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: sg_adahack
        - Key: Project
          Value: !Ref TagsProject
        - Key: Team
          Value: !Ref TagsTeam
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroupAdaHack
      UserData:
        Fn::Base64:  |
          #!/bin/bash
          sudo yum update -y
          sudo yum install docker -y
          sudo yum install git -y
          sudo service docker start
          sudo systemctl enable docker
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo git clone https://github.com/nglai/ada-hack-devops /appAda
          cd /appAda
          sudo docker-compose up -d
      Tags:
        - Key: Name
          Value: instance_adahack
        - Key: Project
          Value: !Ref TagsProject
        - Key: Team
          Value: !Ref TagsTeam